# web.yml
---
- hosts: deb
  user: vagrant

  tasks:
    - name: remove php5.6
      apt:
        name: php5.6
        state: absent
#        autoremove: yes
      sudo: yes

    - name: remove php5.6 configs
      shell: apt-get autoremove -y
      sudo: yes

    - name: install php7.2
      apt:
        name: php7.2
        force: yes
      sudo: yes

